// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tbr_data_api.DataContext;

namespace tbr_data_api.Migrations
{
    [DbContext(typeof(MessageContext))]
    partial class MessageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tbr_common.Poco.Conversation", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("conversationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("recipientId")
                        .HasColumnType("int");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<string>("uploadKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.HasKey("_id");

                    b.ToTable("Conversation");
                });

            modelBuilder.Entity("tbr_common.Poco.MediaUrl", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("messageId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("_id");

                    b.HasIndex("messageId");

                    b.ToTable("MediaUrl");
                });

            modelBuilder.Entity("tbr_common.Poco.Message", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("conversationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("externalId")
                        .HasColumnType("int");

                    b.Property<int>("recipientId")
                        .HasColumnType("int");

                    b.Property<int>("senderId")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uploadKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.HasKey("_id");

                    b.HasIndex("conversationId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("tbr_common.Poco.MediaUrl", b =>
                {
                    b.HasOne("tbr_common.Poco.Message", "Message")
                        .WithMany("MediaUrls")
                        .HasForeignKey("messageId");
                });

            modelBuilder.Entity("tbr_common.Poco.Message", b =>
                {
                    b.HasOne("tbr_common.Poco.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("conversationId");
                });
#pragma warning restore 612, 618
        }
    }
}
